#!/usr/bin/env bash
# The most portable bash shebang

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. "$SCRIPT_DIR/../logger"
. "$SCRIPT_DIR/setup_utils"

verify_non_sudo_user

# Update existing packages
log info "Updating Installed Packages"
sudo apt update
sudo apt upgrade

install_once flatpak
install_once gnome-software-plugin-flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

install_once nvidia-driver

sudo apt autoremove

# Describe manual configuration for bypassing the user prompt during boot
log info "To disable the manual selection in the grub menu during boot,"
log info "  sudo nano /etc/default/grub"
log info "  set GRUB_DEFAULT=0 to set the default setting"
log info "  set GRUB_TIMEOUT=0 to instantly auto select the default setting"
log info "  sudo update-grub"

log info "restart the computer when ready"

