#!/usr/bin/env bash
# The most portable bash shebang

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. "$SCRIPT_DIR/../logger"

installOnce () {
  if [[ -z $1 ]]; then
    log error "function installOnce was run without parameters"
    log info "  Example usage:"
    log info "    installOnce \"vim\""
    return -1
  fi

  log info "installing $1"

  if isInstalled $1; then
    log info "$1 is already installed"
    return 1
  else
    sudo apt install "$1"
    return 0
  fi
}

isInstalled () {
  if [[ -z "$1" ]]; then
    log error "function isInstalled requires the name of the package to check"
    log info "  Example usage:"
    log info "    isInstalled \"vim\""
    return -1
  fi

  if [[ $(dpkg -s "$1" 2>/dev/null | grep Status) == *"installed" ]]; then
    return 0
  else
    return 1
  fi
}

# Check if running as sudo
if [ "$EUID" -eq 0 ]; then
  log fail "script cannot be ran as sudo"
  log info "  Exiting"

  exit 1
fi

# Update existing packages
log info "Updating Installed Packages"
sudo apt update
sudo apt upgrade

installOnce flatpak
installOnce gnome-software-plugin-flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

installOnce nvidia-driver

sudo apt autoremove

# Describe manual configuration for bypassing the user prompt during boot
log info "To disable the manual selection in the grub menu during boot,"
log info "  sudo nano /etc/default/grub"
log info "  set GRUB_DEFAULT=0 to set the default setting"
log info "  set GRUB_TIMEOUT=0 to instantly auto select the default setting"
log info "  sudo update-grub"

log info "restart the computer when ready"

