#!/usr/bin/env bash
# The most portable bash shebang

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. "$SCRIPT_DIR/../logger"
. "$SCRIPT_DIR/setup_utils"

add_ytdlp_to_path () {
  ADD_LOCAL_BIN_TO_PATH_LINE="export PATH=\$PATH:/home/$USER/.local/bin"
  if ! grep -q "$ADD_LOCAL_BIN_TO_PATH_LINE" $BASHRC_PATH; then
    echo "" >> $BASHRC_PATH
    echo "# add yt-dlp folder to path" >> $BASHRC_PATH
    echo "$ADD_LOCAL_BIN_TO_PATH_LINE" >> $BASHRC_PATH
  fi
}

configure_terminal_autocomplete_cycling () {
  BASHRC_PATH="/home/$USER/.bashrc"
  AUTOCOMPLETE_CYCLING_CONFIGURATION_LINE="bind TAB:menu-complete"

  if ! grep -q "$AUTOCOMPLETE_CYCLING_CONFIGURATION_LINE" $BASHRC_PATH; then
    echo "" >> $BASHRC_PATH
    echo "# cycle through tab autocomplete options instead of stopping at shared substrings" >> $BASHRC_PATH
    echo "$AUTOCOMPLETE_CYCLING_CONFIGURATION_LINE" >> $BASHRC_PATH
    log info "Configured .bashrc to cycle through autocomplete options"
  fi
}

install_flatpak_general_apps () {
  flatpak install flathub org.kde.krita
  flatpak install flathub org.keepassxc.KeePassXC
  flatpak install flathub org.videolan.VLC
  
  # Optionals
  if ! is_installed "com.brave.Browser"; then
    if is_user_approved "would you like to install brave browser?"; then
      flatpak install flathub com.brave.Browser
    fi
  else
    log info "brave browser is already installed"
  fi
  
  if ! is_installed "org.chromium.Chromium"; then
    if is_user_approved "would you like to install chromium browser?"; then
      flatpak install flathub org.chromium.Chromium
    fi
  else
    log info "chromium browser is already installed"
  fi
}

install_general_packages () {
  install_once curl
  install_once ffmpeg
  install_once fonts-noto-cjk
  
  if install_once git; then
    git config --global user.name "Shen Yang"
    git config --global user.email "shenyang128@proton.me"
    log info "configured email and name for git"
  fi
  
  install_once p7zip-full

  if install_once vim; then
    set_vim_as_default_editor
  fi
  
  if ! test -f "/home/$USER/.local/bin/yt-dlp"; then
    log info "installing yt-dlp"
    log info "yt-dlp has an asynchronous download"
    log info "continue after the download"
    mkdir -p /home/$USER/.local/bin
    curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /home/$USER/.local/bin/yt-dlp
    wait_for_user
    chmod a+rx "/home/$USER/.local/bin/yt-dlp"
    
    add_ytdlp_to_path
  fi
  
  # Optional Section
  if ! is_installed macchanger; then
    if is_user_approved "Would you like to install macchanger?"; then
      install_once macchanger
    fi
  fi
}

print_keyboard_shortcut_hints () {
  log info "The following keybinds should be modified"
  log info "  Go to settings -> keybinds -> navigation"
  log info "  Hide All Normal Windows -> Super + D"
  log info "  Switch Windows -> Alt + Tab"
  log info "    This will unbind Alt + Tab from switching applications"
}

set_vim_as_default_editor () {
  log info "Configuring vim as the default editor"
  log warn "Pick vim.basic not vim.tiny"
  sudo update-alternatives --config editor
  git config --global core.editor vim
}

verify_non_sudo_user
configure_terminal_autocomplete_cycling
install_general_packages
install_flatpak_general_apps

log info "Clean Up"
sudo apt autoremove

print_keyboard_shortcut_hints

