#!/usr/bin/env bash
# The most portable bash shebang

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

. "$SCRIPT_DIR/../logger"
. "$SCRIPT_DIR/setup_utils"

add_github_cli_repo () {
  # from https://github.com/cli/cli/blob/trunk/docs/install_linux.md
  sudo mkdir -p -m 755 /etc/apt/keyrings
  out=$(mktemp)
  wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg
  cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
  sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  sudo apt update
}

add_postgres_repo () {
  log info "Adding the postgres repo"
  sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

  # Add the repo key to the keyring:
  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor | sudo tee /usr/share/keyrings/postgres-archive-keyring.gpg

  log info "  Open /etc/apt/sources.list.d/pgdg.list with super user permissions so you are allowed to write to the file"
  log info "    Example using vim:"
  log info "      sudo vim /etc/apt/sources.list.d/pgdg.list"
  log info "    Paste \"[signed-by=/usr/share/keyrings/postgres-archive-keyring.gpg]\" between \"deb\" and \"http://apt.postgresql...\""
  log info "      Example: deb [signed-by=/usr/share/keyrings/postgres-archive-keyring.gpg] http://apt.postgresql.org/pub/repos/apt jammy-pgdg main"
  log info "    Save the file"
  log info "  Continue after the key configuration"
  wait_for_user
}

configure_casa () {
  cd ~/Projects/casa

  log info "configuring casa"
  bundle
  # A hack to get the setup to work
  bundle exec rails db:reset
  bundle exec rails db:migrate
  bundle exec rake after_party:run

  npm i
  npm run build
  npm run build:css
}

configure_postgres_12 () {
  log info "staring postgres 12 service"
  sudo systemctl start postgresql@12-main

  log info "creating postgres user"
  sudo -u postgres psql -c "CREATE USER $USER WITH CREATEDB"
}

configure_github_ssh_keys () {
  if ! test -f "/home/$USER/.ssh/id_ed25519"; then
    log info "setting up ssh keys for github"
    log info "  don't set a file name for the key"
    log info "  don't set a passphrase for the key"
    ssh-keygen -t ed25519 -C "shenyang128@proton.me"
    eval "$(ssh-agent -s)"
    eval ssh-add ~/.ssh/id_ed25519
    log info "go to https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account and follow the instructions"
    log info "continue when ready"
    wait_for_user
  fi
}

download_casa () {
  log info "cloning casa into ~/Projects/casa"
  mkdir -p ~/Projects
  cd ~/Projects

  git clone git@github.com:FireLemons/casa.git
}

install_flatpak_developer_apps () {
  if ! is_installed "com.slack.Slack"; then
    if is_user_approved "Would you like to install slack?"; then
      flatpak install flathub com.slack.Slack
    fi
  fi
}

install_nodejs () {
  if ! nvm --version &> /dev/null; then
    log info "Setting up a node environment"
    log info "  find the nvm install command at https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating"
    log info "  it relies on the version number which updates frequently"
    log info "    continue after nvm is installed"
    wait_for_user

    # Load nvm
    export NVM_DIR="/home/$USER/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

    log info "  installing latest LTS node version"
    nvm install --lts
    log info "  setting latest LTS node version as default"
    nvm alias default lts/*
  else
    log info "nvm is installed and it is assumed that nodejs has been set up"
  fi
}

install_postgres_12 () {
  log info "Installing postgres 12"

  sudo apt update
  sudo apt install libpq-dev
  sudo apt install postgresql-12
}

install_rbenv () {
  log info "Installing rbenv"

  install_once libyaml-dev
  install_once zlib1g-dev

  git clone https://github.com/rbenv/rbenv.git $RBENV_ROOT

  ADD_RBENV_BIN_TO_PATH_LINE="export PATH=\$PATH:/home/$USER/.rbenv/bin"
  if ! grep -q "$ADD_RBENV_BIN_TO_PATH_LINE" $BASHRC_PATH; then
    echo "" >> $BASHRC_PATH
    echo "# add rbenv to path" >> $BASHRC_PATH
    echo "$ADD_RBENV_BIN_TO_PATH_LINE" >> $BASHRC_PATH
  fi

  export PATH=$PATH:/home/flysy/.rbenv/bin

  eval "$(rbenv init - --no-rehash bash)"

  git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)/plugins/ruby-build"
}

install_ruby () {
  log info "Installing ruby"
  rbenv install "$(cat ~/Projects/casa/.ruby-version)"
}

install_vscode () {
  log info "Installing VSCode"
  log info "  The flatpak of vscode cannot be used because it cannot directly interface with sdks outside of the flatpak environment"
  log info "  go to https://code.visualstudio.com/download and get the .deb file"
  log info "  sudo apt install path/to/.deb"
  wait_for_user

  log info "To change the tab size to 2 spaces, go to settings then search tabsize"
}

verify_non_sudo_user
install_flatpak_developer_apps
configure_github_ssh_keys
install_nodejs

if ! is_installed gh; then
  if is_user_approved "Would you like to install the github cli?"; then
    add_github_cli_repo
    sudo apt install gh
    gh auth login
  else
    log info "gh is already installed"
  fi
fi

if is_user_approved "Would you like to set up a casa environment?"; then
  if ! is_installed heroku; then
    log info "Installing heroku cli"
    curl https://cli-assets.heroku.com/install.sh | sh
    heroku login
  fi

  if ! is_installed postgresql-12; then
    add_postgres_repo
    install_postgres_12
    configure_postgres_12
  fi

  if [ ! -d ~/Projects/casa ]; then
    download_casa
  fi

  RBENV_ROOT="$HOME/.rbenv"
  if [ ! -d $RBENV_ROOT ]; then
    install_rbenv
    install_ruby
  fi
  
  configure_casa
fi

log info "Clean Up"
sudo apt autoremove

