#!/bin/bash

if [ $# -lt 1 ] 
then
    echo "Error: missing url"
    echo "Usage:"
    echo "  download <youtube/crunchyroll url>"
    echo "  download -m <youtube url>"
    echo "  download -p $'...User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0\nAccept: */*...' \"Video URL\" \"output.mp4\""
    echo "  download <twitch url> <start time(HH:MM:SS)> <end time(HH:MM:SS)>"
    echo "  download <twitch url> <start time(HH:MM:SS)> <end time(HH:MM:SS)> <file name>"
    exit 1
fi

# Download a youtube video
if [[ "$1" == http?(s)://www.youtube.com* ]];then
    youtube-dl -f "298+140/136+140" "$1"
    exit 0

# Download music from youtube
elif [[ "$1" = "-m" ]];then
    if [ $# -lt 2 ];then
        echo "ERROR: No video url."
        exit 1
    fi

    youtube-dl -f 140 -o "~/Music/%(title)s.%(ext)s" "$2"
    exit 0

# Download a video from a url with headers
elif [[ "$1" == "-p" ]];then
    if [ $# -lt 4 ];then
        echo "ERROR: Missing video url, headers, or output file name"
        exit 1
    fi

    ffmpeg -headers "$2" -i "$3" -c copy "$4"
    exit 0

# Download a twitch VOD
elif [[ "$1" == http?(s)://www.twitch.tv* ]];then
    if [ $# -ge 3 ]
    then
      cd ~/Videos/VODs/

      start=`date +%s -d $2`
      end=`date +%s -d $3`
      endCorrected=`expr ${end} - ${start}`
      fileName=`[ $# -ge 4 ] && echo "$4" || echo "twitchVod"`

      ffmpeg -ss "$2" -i `youtube-dl -f 720p60/720p60-0 -g "$1"` -t "$endCorrected" -c copy "$fileName".mp4
      echo "Saved video to ~/Videos/VODs/${fileName}.mp4"

    else
      youtube-dl -f 720p60 -o "~/Videos/VODs/%(title)s.%(ext)s" $1
      echo "Saved video to ~/Videos/VODs/"

    fi

    exit 0
elif [[ "$1" == http?(s)://www.crunchyroll.com* ]];then 
    youtube-dl --write-sub --sub-lang enUS "$1"
else
    echo "Unsupported Option"
    exit 0
fi
