#!/bin/bash

if [ $# -lt 1 ]
then
  echo "Error: missing file name"
  echo "Example usage:"
  echo "  newhtml <file name>"
  exit 1

fi

echo "<!DOCTYPE html>
<html>
  <head>
    <title></title>

  </head>
  <body>

  </body>
</html>" > "$1".html
exit 0
